<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('ProfileIndustry', 'doctrine');

/**
 * BaseProfileIndustry
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $user_id
 * @property integer $industry_id
 * @property enum $type_id
 * @property User $User
 * @property Industry $Industry
 * 
 * @method integer         getId()          Returns the current record's "id" value
 * @method integer         getUserId()      Returns the current record's "user_id" value
 * @method integer         getIndustryId()  Returns the current record's "industry_id" value
 * @method enum            getTypeId()      Returns the current record's "type_id" value
 * @method User            getUser()        Returns the current record's "User" value
 * @method Industry        getIndustry()    Returns the current record's "Industry" value
 * @method ProfileIndustry setId()          Sets the current record's "id" value
 * @method ProfileIndustry setUserId()      Sets the current record's "user_id" value
 * @method ProfileIndustry setIndustryId()  Sets the current record's "industry_id" value
 * @method ProfileIndustry setTypeId()      Sets the current record's "type_id" value
 * @method ProfileIndustry setUser()        Sets the current record's "User" value
 * @method ProfileIndustry setIndustry()    Sets the current record's "Industry" value
 * 
 * @package    symfony
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseProfileIndustry extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('profile_industry');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('user_id', 'integer', 4, array(
             'type' => 'integer',
             'unsigned' => true,
             'notnull' => true,
             'default' => 0,
             'length' => 4,
             ));
        $this->hasColumn('industry_id', 'integer', 4, array(
             'type' => 'integer',
             'unsigned' => true,
             'notnull' => true,
             'default' => 0,
             'length' => 4,
             ));
        $this->hasColumn('type_id', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 0,
              1 => 1,
             ),
             'notnull' => true,
             'default' => 0,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('User', array(
             'local' => 'id',
             'foreign' => 'user_id',
             'onDelete' => 'CASCADE',
             'onUpdate' => 'CASCADE'));

        $this->hasOne('Industry', array(
             'local' => 'id',
             'foreign' => 'industry_id',
             'onDelete' => 'CASCADE',
             'onUpdate' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}