<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Sponsor', 'doctrine');

/**
 * BaseSponsor
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $position
 * @property string $company
 * @property string $image_full
 * @property string $image_small
 * 
 * @method integer getId()          Returns the current record's "id" value
 * @method string  getPosition()    Returns the current record's "position" value
 * @method string  getCompany()     Returns the current record's "company" value
 * @method string  getImageFull()   Returns the current record's "image_full" value
 * @method string  getImageSmall()  Returns the current record's "image_small" value
 * @method Sponsor setId()          Sets the current record's "id" value
 * @method Sponsor setPosition()    Sets the current record's "position" value
 * @method Sponsor setCompany()     Sets the current record's "company" value
 * @method Sponsor setImageFull()   Sets the current record's "image_full" value
 * @method Sponsor setImageSmall()  Sets the current record's "image_small" value
 * 
 * @package    symfony
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSponsor extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('sponsor');
        $this->hasColumn('id', 'integer', 2, array(
             'type' => 'integer',
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 2,
             ));
        $this->hasColumn('position', 'string', 1, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 1,
             ));
        $this->hasColumn('company', 'string', 150, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 150,
             ));
        $this->hasColumn('image_full', 'string', 150, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 150,
             ));
        $this->hasColumn('image_small', 'string', 150, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 150,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}