<?php

/**
 * CityTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CityTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CityTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('City');
    }
    
    public function getCityList($param=array()){
      $q = Doctrine_Query::create()
        ->from('City c')
        ->leftJoin('c.State s');
      
      $pager = new sfDoctrinePager('City', 10);
      $pager->setQuery($q);
      $pager->setPage($param['curPage']);
      $pager->init();
      return $pager;
    }
    
    public function getCitiesByState($state_id=0){
      $q = Doctrine_Query::create()
        ->from('City c');
      if($state_id){
        $q->where('c.state_id = ?',$state_id);
      }
      $q->orderBy('c.name ASC');
      return $q->execute();
    }
		
		public function getAllCities(){
      $q = Doctrine_Query::create()
        ->from('City');
      $fetch = $q->fetchArray(array(),Doctrine::HYDRATE_ARRAY);
      return array_merge($fetch);
    }
}