<?php

/**
 * CityTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CityTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CityTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('City');
    }
		
		public function getAllCities(){
      $q = Doctrine_Query::create()
        ->from('City');
      $fetch = $q->fetchArray(array(),Doctrine::HYDRATE_ARRAY);
      return array_merge($fetch);
    }
}