<?php

/**
 * EventAttendeeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EventAttendeeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object EventAttendeeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('EventAttendee');
    }
}