<?php

/**
 * EventAttendeeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EventAttendeeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object EventAttendeeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('EventAttendee');
    }
    
    public function getAllAttendee($event_id,$param=array()){
      $q = Doctrine_Query::create()
        ->from('EventAttendee ea')
        ->innerJoin('ea.User u')
        ->innerJoin('u.Profile p')
        ->leftJoin('p.City c')
        ->where('ea.event_id = ?',$event_id);
      
      if($param['email']){
        $q->andWhere('u.email = ?',$param['email']);
      }
      
      if($param['company']){
        $q->andWhere('p.company LIKE ?','%'.$param['company'].'%');
      }
      
      if($param['keyword']){
        $q->andWhere('u.fname LIKE ?','%'.$param['keyword'].'%');
        $q->orWhere('u.lname LIKE ?','%'.$param['keyword'].'%');
        $q->orWhere('p.ido LIKE ?','%'.$param['keyword'].'%');
        $q->orWhere('p.to_meet LIKE ?','%'.$param['keyword'].'%');
      }
      
      
      $pager = new sfDoctrinePager('Event', 6);
      $pager->setQuery($q);
      $pager->setPage($param['curPage']);
      $pager->init();
      return $pager;
    }
}