<?php

/**
 * EventTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EventTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object EventTable
     */
    public static function getInstance(){
        return Doctrine_Core::getTable('Event');
    }
    
    public static function getAllEvent(){
      $pager = new sfDoctrinePager('Event', 2);
      $q = Doctrine_Query::create()
        ->select('e.*,(SELECT count(*) FROM eventAttendee ea WHERE ea.event_id = e.id) as countAttendee')
        ->from('Event e')
        ->leftJoin('e.City c')
        ->leftJoin('c.State s')
        ->orderBy('e.event_date DESC');
      //return $q->execute();
      $pager->setQuery($q);
      $pager->setPage(1);
      $pager->init();
      return $pager;
    }
}