<?php

/**
 * IndustryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class IndustryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object IndustryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Industry');
    }
}