<?php

/**
 * ProfileIndustryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProfileIndustryTable extends Doctrine_Table{
    /**
     * Returns an instance of this class.
     *
     * @return object ProfileIndustryTable
     */
    public static function getInstance(){
        return Doctrine_Core::getTable('ProfileIndustry');
    }

    public function getProfileIndustry($user_id,$type_id=0,$industry_id=0){
      $q = Doctrine_Query::create()
        ->from('ProfileIndustry pi')
        ->leftJoin('pi.Industry i')
        ->where('pi.user_id = ?',$user_id)
        ->andWhere('pi.type_id = ?',$type_id);
      
      if($industry_id){
        $q->andWhere('pi.industry_id = ?',$industry_id);
        return $q->execute();
      }
      
      return $q->execute();
    }
		
		public function getUsersIndustry($uid){
		
		$fetch = Doctrine_Core::getTable('ProfileIndustry')
      ->createQuery('a')
			->where('a.user_id = ?', $uid)
      ->execute();
      return $fetch;
    }
}