<?php

/**
 * UserTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UserTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object UserTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('User');
    }
    
    function getUserByAppId($app_id,$app_type=1){
     $q = Doctrine_Query::create()
            ->from('User u')
        ->where('u.app_id = ?',$app_id)
        ->andWhere('u.app_type = ?',$app_type);
      return $q->fetchOne(array(),Doctrine::HYDRATE_ARRAY);
    }
}