all:
  stylesheets: [jquery.fancybox.css,http://code.jquery.com/ui/1.9.1/themes/smoothness/jquery-ui.css,jquery-ui-timepicker-addon.css]
  javascripts: [fancybox/source/jquery.fancybox.js,http://code.jquery.com/ui/1.9.1/jquery-ui.min.js,jquery-ui-timepicker-addon.js,jquery-ui-sliderAccess.js]